# Generated by Django 5.2.5 on 2026-03-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('service_type', models.CharField(choices=[('sms', 'SMS Service'), ('email', 'Email Service'), ('payment', 'Payment Gateway'), ('storage', 'Cloud Storage'), ('ai', 'AI Service'), ('other', 'Other')], max_length=20, verbose_name='service type')),
                ('base_url', models.URLField(verbose_name='base URL')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API key')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='secret key')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('config', models.JSONField(default=dict, verbose_name='configuration')),
                ('webhook_url', models.URLField(blank=True, verbose_name='webhook URL')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='webhook secret')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='core.school')),
            ],
            options={
                'verbose_name': 'API integration',
                'verbose_name_plural': 'API integrations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('version', models.CharField(max_length=20, verbose_name='version')),
                ('extension_type', models.CharField(choices=[('academic', 'Academic'), ('financial', 'Financial'), ('communication', 'Communication'), ('integration', 'Integration'), ('utility', 'Utility')], max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('error', 'Error')], default='inactive', max_length=20, verbose_name='status')),
                ('settings', models.JSONField(default=dict, verbose_name='settings')),
                ('dependencies', models.ManyToManyField(blank=True, to='extensions.extension')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='core.school')),
            ],
            options={
                'verbose_name': 'extension',
                'verbose_name_plural': 'extensions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('event_type', models.CharField(choices=[('student.created', 'Student Created'), ('student.updated', 'Student Updated'), ('invoice.created', 'Invoice Created'), ('invoice.paid', 'Invoice Paid'), ('attendance.created', 'Attendance Created'), ('grade.created', 'Grade Created'), ('custom', 'Custom Event')], max_length=50, verbose_name='event type')),
                ('target_url', models.URLField(verbose_name='target URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='secret')),
                ('headers', models.JSONField(default=dict, verbose_name='headers')),
                ('retry_count', models.IntegerField(default=3, verbose_name='retry count')),
                ('timeout', models.IntegerField(default=30, verbose_name='timeout (seconds)')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='core.school')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
                'ordering': ['name'],
            },
        ),
    ]
