# Generated by Django 5.2.5 on 2026-03-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='assessment type')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in percentage', max_digits=5, verbose_name='weight')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'assessment type',
                'verbose_name_plural': 'assessment types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('period', models.CharField(blank=True, max_length=50, null=True, verbose_name='period')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='grade')),
                ('minimum_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='minimum percentage')),
                ('maximum_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='maximum percentage')),
                ('points', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='points')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['minimum_percentage'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='grade scale')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'grade scale',
                'verbose_name_plural': 'grade scales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('term', models.CharField(max_length=50, verbose_name='term')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total marks')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='marks obtained')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='percentage')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='rank')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='remarks')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name': 'report card',
                'verbose_name_plural': 'report cards',
                'ordering': ['-academic_year', 'term', 'student'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='marks obtained')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('is_absent', models.BooleanField(default=False, verbose_name='absent')),
            ],
            options={
                'verbose_name': 'student assessment',
                'verbose_name_plural': 'student assessments',
                'ordering': ['assessment', 'student'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10, verbose_name='status')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='remarks')),
            ],
            options={
                'verbose_name': 'student attendance',
                'verbose_name_plural': 'student attendances',
                'ordering': ['attendance', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='assessment name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='maximum marks')),
                ('date', models.DateField(verbose_name='date')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.classsubject')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['-date'],
            },
        ),
    ]
