# Generated by Django 5.2.5 on 2026-03-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_initial'),
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment.assessmenttype'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.classsubject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='taken_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.gradescale'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.grade'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='assessment.attendance'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_subject', 'date', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together={('assessment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('attendance', 'student')},
        ),
    ]
